#include "Profiles.h"
#include <algorithm>
#include <sstream>
namespace tf {
const Profile& profile(int style) {
 static const std::array<Profile,styleCount> all{{
 {120,Minor,.66,.6,{0,5,2,6},{0,0,2,4},"X.x.X.x.X.xxX.x.","X.....x.X..x....","....X.......X...",2,false,"Low spiccato strings, short brass, synth pulse, sub and ensemble drums","Driven / urgent","Keep the low ostinato narrow. Give the lead a clear register above it. Layer attack, body and sub on major hits; shorten the low release before the next bass note.","https://www.evenant.com/articles/making-your-music-more-cinematic-hits-ostinatos-and-rhythms"},
 {100,Major,.62,.45,{0,4,5,3},{0,2,4,6},"X.x.X.x.X.x.X.x.","X.......X.......","....X.......X...",2,false,"String ostinato, horn theme, open strings, low brass and timpani","Heroic / expansive","Build the theme in octaves only when it needs weight. Keep thirds out of the deepest bass layer. Match note length and accents across short strings and brass.","https://www.evenant.com/courses/trailer-orchestration"},
 {112,Minor,.7,.75,{0,3,5,4},{0,2,4,2},"XxxxXxxxXxxxXxxx","X.......x.......","............x...",1,false,"Close piano, chamber strings, cello pulse and restrained ensemble drums","Elegant / propulsive","Use an identifiable arpeggio cell and changing inversions. Keep pedal and room tails short enough to preserve subdivision clarity; reserve the biggest percussion for the backend.","https://www.universalproductionmusic.com/discover/albums/41480/neoclassical-trailer"},
 {108,Minor,.4,.35,{0,0,5,0},{0,1,0,4},"X...x.X...x.X...","X.........x.....","........X.......",4,true,"Muted strings, ticking texture, sub pulse, dry metal accents","Tense / controlled","Hold a pedal while the upper detail changes. Leave room around dialogue. A single recurring metallic sound can carry more identity than several competing loops.","https://www.evenant.com/articles/10-essential-trailer-music-tips"},
 {78,Phrygian,.28,.45,{0,0,1,0},{0,1,0,3},"X.....x....X....","X...............","..........x.....",4,true,"Bowed metal, detuned piano, low drone, string harmonics and isolated impacts","Dread / unstable","Contrast quiet texture with short shocks. Use the flattened second sparingly against the root. Leave intentional gaps; do not fill every gap with a riser.","https://composer.spitfireaudio.com/en/articles/marco-beltrami-used-shepard-tones-to-create-tension-on-a-quiet-place-part-ii"},
 {76,Major,.4,.3,{0,4,5,3},{4,2,0,2},"X...x...X...x...","X...............","........x.......",2,true,"Felt piano, solo cello, warm strings, soft pulse and restrained cymbal swells","Intimate / hopeful","Establish a singable piano idea before widening the strings. Use velocity shaping on piano and an expression curve on sustaining patches. Preserve dynamic headroom for the emotional lift.","https://blog.native-instruments.com/watch-how-to-make-neo-classical/"},
 {126,Dorian,.65,.8,{0,0,3,6},{0,4,1,0},"X..X..X.X..X..X.","X.....X...X.....","........X.......",2,true,"Sequenced synth, processed strings, metallic percussion, filtered drone","Futuristic / mechanical","Keep one signature pulse dominant. Contrast a stable sub with moving upper harmonics. Automate the texture's tone at act boundaries rather than adding a new layer on every bar.","https://blog.native-instruments.com/jacob-yoffee-on-scoring-movie-trailers/"},
 {100,Major,.65,.5,{0,4,5,3},{0,2,4,2},"X.x.X.xxX.x.X.xx","X.....X.X.....X.","....X.......X...",1,false,"Piano hook, synth bass, pop drums, strings and clap accents","Anthemic / immediate","Keep the hook easy to identify after one listen. Use a clear backbeat and bass pocket. Build the final chorus with octave support and wider voicing, while leaving the hook unchanged.","https://audiomachine.com/trailers/"},
 {92,Minor,.6,.65,{0,0,5,6},{0,0,2,0},"X..x..X...x.X..x","X.....X...x..X..","........X.......",2,true,"808-style bass, dry kick, clap, brass stab and ticking hats","Swagger / confident","Prioritise the kick-bass relationship and silence between stabs. Keep the snare in half time. Add a brief hat turnaround at a phrase end, not a continuous roll under the whole cue.","https://search.westonemusic.com/album/fem-053/champions"},
 {132,Phrygian,.72,.7,{0,0,1,6},{0,0,1,0},"X..X..X.X..X..X.","X..X....X..X....","....X.......X...",2,false,"Distorted synth bass, low guitar chugs, metal hits and short strings","Aggressive / relentless","Make the repeated rhythm the identity. Choose one low-frequency owner per hit. Use parallel distortion for texture and keep the dry transient audible; cut the distorted tail at the edit.","https://megatrax.com/music/trailers"},
 {72,Minor,.35,.35,{0,5,2,6},{4,2,0,0},"X.......x...x...","X...............","........X.......",2,true,"Exposed piano, low pulse, intimate lead placeholder and cinematic drums","Haunting / familiar","This preset creates an original placeholder hook, not a song cover. For a licensed cover, preserve your chosen song's recognisable hook while reducing accompaniment in the opening and rebuilding the backend.","https://audiomachine.com/trailers/"},
 {132,Major,.7,.65,{0,3,4,0},{0,2,4,5},"XxxXxxXxXxxXxxXx","X.......X.......","....X.......X...",1,false,"Light strings, woodwind-like lead, harp arpeggio, horns and orchestral percussion","Wonder / playful adventure","Let the agile upper pattern answer a broader theme. Keep low percussion light in the opening. Use a short fill into a bright arrival and reserve the largest brass voicing for the final lift.","https://alibimusic.com/track/adventure-neoclassical-royal-games-full"},
 {112,Dorian,.45,.55,{0,3,0,4},{0,2,1,0},"X..x..X...x..X..","X.......x.......","....x.......X...",1,false,"Pizzicato strings, mallet hook, light bass, brush-like drums and dry clicks","Quirky / mischievous","Use question-and-answer phrases with clear pauses. Dry short notes help visual comedy land. Keep the final button small enough to leave space for a spoken joke.","https://audiomachine.com/trailers/"},
 {88,Major,.38,.35,{0,5,3,4},{0,2,4,2},"X...x...X...x...","X...............","............x...",2,true,"Organic piano, soft strings, acoustic pulse, warm synth bed","Human / reflective","Build from an intimate source and retain its detail as the arrangement grows. Let small changes in voicing and register carry the development before adding drums.","https://audiomachine.com/music/latest/here-and-now/"},
 {118,Minor,.7,.6,{0,6,5,6},{0,0,4,2},"X.x.X.xxX.x.X.xx","X.....X.X.x.....","....X.......X...",1,false,"Low guitar riff placeholder, bass, rock kit, brass and large toms","Defiant / powerful","Treat riff and drums as a band. Lock bass attacks to the kick and leave a pocket for the snare. Add orchestral sustain above the riff rather than doubling every guitar note.","https://www.westonemusic.com/license-background-music/"},
 {96,Minor,.32,.3,{0,0,3,0},{0,0,1,0},"X.......x.X.....","X...............","............x...",4,true,"Single-note piano, ticking percussion, filtered pulse, drone and dry impact","Investigative / uneasy","Leave space for factual dialogue. Evolve one small motif through register and timbre. Keep the arrival restrained; do not default to an epic ending for a grounded story.","https://www.evenant.com/articles/10-essential-trailer-music-tips"}
 }};
 return all[size_t(std::clamp(style,0,styleCount-1))];
}
std::string productionNotes(const Settings& input) {
 auto s=sanitise(input);auto& p=profile(s.style);std::ostringstream o;
 o<<styles[size_t(s.style)]<<" / PRODUCTION PLAN\n\n"<<p.production<<"\n\nPALETTE\n"<<p.palette;
 o<<"\n\nARRANGEMENT\nSetup: establish one recognisable hook and a texture.\nBuild: introduce rhythmic support in stages; retain the same hook.\nClimax I: fuller rhythm, voice-led harmony and stronger accents.\n"<<(s.finalLift?"Climax II: lift the hook's register and intensity, then cut to the button.":"Resolution: remove motion and leave space around the final button.");
 o<<"\n\nDAW EXECUTION\nUse short articulations for the ostinato; keep the bass mostly monophonic. Put the motif in its own register. Balance the cue quietly before adding limiting. Check low-end overlap, reverb tails at edits and mono compatibility. Export separate stems and a clean ending when the delivery brief asks for them.";
 o<<"\n\nDYNAMICS\n"<<(s.expression?"CC1/CC11 curves are included for Chords and Atmosphere. Confirm your instrument's mapping; the sketch synth does not reproduce those controllers.":"Optional CC1/CC11 curves are off. Enable them only when your sustaining patches use those controllers.");
 o<<"\n\nREFERENCE\n"<<p.source<<"\n\nGenre patterns and musical choices are original design suggestions informed by research, not transcriptions of a trailer. References are listening/research links; no audio is embedded or analysed by this plug-in.";
 return o.str();
}
}
